### ISSUE TITLE
How to compile the judge program?

### ISSUE THREAD

**Issue by MGithubGA** [ailab-pku/Chinese-Standard-Mahjong#1]
Hi @zhouhaoyu ! Thanks for your great work! 👍

I'm currently using Macbook, and try to compile the judge program. [This](https://github.com/ailab-pku/Chinese-Standard-Mahjong/tree/master/judge) folder only contains a source file.

Could you please provide how to compile or use the judge program?

Thanks.

**Comment by lpaladin** [comment]
Hi @MGithubGA ,

Sorry for the late reply.
If you are to compile the judge on your own, you may need to:
* Install boost header-only library to your system include dir (e.g. /usr/local/include);
* Extract http://www.botzone.org.cn/static/JsonCPP_modified2.zip under the same directory as the judge program, or manually install other release of jsoncpp;
* Put all files under https://github.com/ailab-pku/Chinese-Standard-Mahjong/tree/master/fan-calculator-usage/ChineseOfficialMahjongHelper/Classes/mahjong-algorithm into a directory named `MahjongGB`
* Compile the judge cpp file using `g++ -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -Wall -mavx -std=c++1z FILENAME.cpp`

**Comment by MGithubGA** [comment]
Thanks
