### ISSUE TITLE
请问你们有模拟器吗？

### ISSUE THREAD

**Issue by GoingMyWay** [ailab-pku/Chinese-Standard-Mahjong#5]
请问，如果要使用model-free训练，你们提供模拟器吗？

**Comment by castor-v-pollux** [comment]
你好，模拟器是指可运行的游戏裁判程序吗？

**Comment by GoingMyWay** [comment]
> 你好，模拟器是指可运行的游戏裁判程序吗？

是的，运行游戏裁判的程序和用来收集经验来做RL训练的模拟器。

**Comment by castor-v-pollux** [comment]
https://github.com/ailab-pku/botzone-local

**Comment by GoingMyWay** [comment]
> https://github.com/ailab-pku/botzone-local

非常感谢。
